### ISSUE TITLE
Please add support for Xcode 5 images.xcassets

### ISSUE THREAD

**Issue by EvgenyKarkan** [jeffhodnett/Unused#20]
If my images are located in images.xcassets folder & I use this folder's sub-folder for image path like [SKTexture textureWithImageNamed:@"Rocket"] - where @"Rocket" is a sub-folder name (which is includes the real png file) - the Unused app marks all the images (which is really used) as unused.

**Comment by jeffhodnett** [comment]
I've updated the project now
