### ISSUE TITLE
isValidImageAtPath seems to be returning the opposite of what it should

### ISSUE THREAD

**Issue by pip8786** [jeffhodnett/Unused#24]
I tried running this on one of my apps and it seemed to execute way to fast with 0 results. I did a bit of digging and notices that it was processing very few images. I think the cause of that is the isValidImageAtPath method was filtering out everything but "system" images (such as icon, default, etc). My guess is the intention was to filter those out, and leaving everything else in. I changed line 342 to this:
`return !(has2xImage || isThirdPartyBundle || isNamedDefault || isNamedIcon || isUniversalImage);` and it seemed to at least process all the images properly. 

Please let me know if this is not the correct assumption.

**Comment by jeffhodnett** [comment]
I think i've fixed this
